 export const proverbs = [
  { ref: "Proverbs 1:5", text: "A wise man will hear, and will increase learning; and a man of understanding shall attain unto wise counsels:" },
  { ref: "Proverbs 1:7", text: "The fear of the LORD is the beginning of knowledge: but fools despise wisdom and instruction." },
  { ref: "Proverbs 1:8", text: "My son, hear the instruction of thy father, and forsake not the law of thy mother:" },
  { ref: "Proverbs 1:10", text: "My son, if sinners entice thee, consent thou not." },
  { ref: "Proverbs 1:23", text: "Turn you at my reproof: behold, I will pour out my spirit unto you, I will make known my words unto you." },
  { ref: "Proverbs 1:33", text: "But whoso hearkeneth unto me shall dwell safely, and shall be quiet from fear of evil." },
  { ref: "Proverbs 2:2", text: "So that thou incline thine ear unto wisdom, and apply thine heart to understanding;" },
  { ref: "Proverbs 2:6", text: "For the LORD giveth wisdom: out of his mouth cometh knowledge and understanding." },
  { ref: "Proverbs 2:7", text: "He layeth up sound wisdom for the righteous: he is a buckler to them that walk uprightly." },
  { ref: "Proverbs 2:8", text: "He keepeth the paths of judgment, and preserveth the way of his saints." },
  { ref: "Proverbs 2:9", text: "Then shalt thou understand righteousness, and judgment, and equity; yea, every good path." },
  { ref: "Proverbs 2:10", text: "When wisdom entereth into thine heart, and knowledge is pleasant unto thy soul;" },
  { ref: "Proverbs 2:11", text: "Discretion shall preserve thee, understanding shall keep thee:" },
  { ref: "Proverbs 2:20", text: "That thou mayest walk in the way of good men, and keep the paths of the righteous." },
  { ref: "Proverbs 3:3", text: "Let not mercy and truth forsake thee: bind them about thy neck; write them upon the table of thine heart:" },
  { ref: "Proverbs 3:5", text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding." },
  { ref: "Proverbs 3:6", text: "In all thy ways acknowledge him, and he shall direct thy paths." },
  { ref: "Proverbs 3:7", text: "Be not wise in thine own eyes: fear the LORD, and depart from evil." },
  { ref: "Proverbs 3:9", text: "Honour the LORD with thy substance, and with the firstfruits of all thine increase:" },
  { ref: "Proverbs 3:13", text: "Happy is the man that findeth wisdom, and the man that getteth understanding." },
  { ref: "Proverbs 3:17", text: "Her ways are ways of pleasantness, and all her paths are peace." },
  { ref: "Proverbs 3:21", text: "My son, let not them depart from thine eyes: keep sound wisdom and discretion:" },
  { ref: "Proverbs 3:24", text: "When thou liest down, thou shalt not be afraid: yea, thou shalt lie down, and thy sleep shall be sweet." },
  { ref: "Proverbs 3:26", text: "For the LORD shall be thy confidence, and shall keep thy foot from being taken." },
  { ref: "Proverbs 3:27", text: "Withhold not good from them to whom it is due, when it is in the power of thine hand to do it." },
  { ref: "Proverbs 4:7", text: "Wisdom is the principal thing; therefore get wisdom: and with all thy getting get understanding." },
  { ref: "Proverbs 4:11", text: "I have taught thee in the way of wisdom; I have led thee in right paths." },
  { ref: "Proverbs 4:13", text: "Take fast hold of instruction; let her not go: keep her; for she is thy life." },
  { ref: "Proverbs 4:18", text: "But the path of the just is as the shining light, that shineth more and more unto the perfect day." },
  { ref: "Proverbs 4:23", text: "Keep thy heart with all diligence; for out of it are the issues of life." },
  { ref: "Proverbs 4:24", text: "Put away from thee a froward mouth, and perverse lips put far from thee." },
  { ref: "Proverbs 4:25", text: "Let thine eyes look right on, and let thine eyelids look straight before thee." },
  { ref: "Proverbs 4:26", text: "Ponder the path of thy feet, and let all thy ways be established." },
  { ref: "Proverbs 5:1", text: "My son, attend unto my wisdom, and bow thine ear to my understanding:" },
  { ref: "Proverbs 5:21", text: "For the ways of man are before the eyes of the LORD, and he pondereth all his goings." },
  { ref: "Proverbs 6:6", text: "Go to the ant, thou sluggard; consider her ways, and be wise:" },
  { ref: "Proverbs 6:16", text: "These six things doth the LORD hate: yea, seven are an abomination unto him:" },
  { ref: "Proverbs 6:20", text: "My son, keep thy father's commandment, and forsake not the law of thy mother:" },
  { ref: "Proverbs 6:23", text: "For the commandment is a lamp; and the law is light; and reproofs of instruction are the way of life:" },
  { ref: "Proverbs 7:2", text: "Keep my commandments, and live; and my law as the apple of thine eye." },
  { ref: "Proverbs 7:4", text: "Say unto wisdom, Thou art my sister; and call understanding thy kinswoman:" },
  { ref: "Proverbs 8:10", text: "Receive my instruction, and not silver; and knowledge rather than choice gold." },
  { ref: "Proverbs 8:11", text: "For wisdom is better than rubies; and all the things that may be desired are not to be compared to it." },
  { ref: "Proverbs 8:17", text: "I love them that love me; and those that seek me early shall find me." },
  { ref: "Proverbs 8:18", text: "Riches and honour are with me; yea, durable riches and righteousness." },
  { ref: "Proverbs 8:32", text: "Now therefore hearken unto me, O ye children: for blessed are they that keep my ways." },
  { ref: "Proverbs 8:33", text: "Hear instruction, and be wise, and refuse it not." },
  { ref: "Proverbs 8:35", text: "For whoso findeth me findeth life, and shall obtain favour of the LORD." },
  { ref: "Proverbs 9:8", text: "Reprove not a scorner, lest he hate thee: rebuke a wise man, and he will love thee." },
  { ref: "Proverbs 9:9", text: "Give instruction to a wise man, and he will be yet wiser: teach a just man, and he will increase in learning." },
  { ref: "Proverbs 9:10", text: "The fear of the LORD is the beginning of wisdom: and the knowledge of the holy is understanding." },
  { ref: "Proverbs 9:11", text: "For by me thy days shall be multiplied, and the years of thy life shall be increased." },
  { ref: "Proverbs 9:12", text: "If thou be wise, thou shalt be wise for thyself: but if thou scornest, thou alone shalt bear it." },
  { ref: "Proverbs 10:4", text: "He becometh poor that dealeth with a slack hand: but the hand of the diligent maketh rich." },
  { ref: "Proverbs 10:7", text: "The memory of the just is blessed: but the name of the wicked shall rot." },
  { ref: "Proverbs 10:9", text: "He that walketh uprightly walketh surely: but he that perverteth his ways shall be known." },
  { ref: "Proverbs 10:11", text: "The mouth of a righteous man is a well of life: but violence covereth the mouth of the wicked." },
  { ref: "Proverbs 10:12", text: "Hatred stirreth up strifes: but love covereth all sins." },
  { ref: "Proverbs 10:14", text: "Wise men lay up knowledge: but the mouth of the foolish is near destruction." },
  { ref: "Proverbs 10:17", text: "He is in the way of life that keepeth instruction: but he that refuseth reproof erreth." },
  { ref: "Proverbs 10:19", text: "In the multitude of words there wanteth not sin: but he that refraineth his lips is wise." },
  { ref: "Proverbs 10:22", text: "The blessing of the LORD, it maketh rich, and he addeth no sorrow with it." },
  { ref: "Proverbs 10:28", text: "The hope of the righteous shall be gladness: but the expectation of the wicked shall perish." },
  { ref: "Proverbs 10:29", text: "The way of the LORD is strength to the upright: but destruction shall be to the workers of iniquity." },
  { ref: "Proverbs 11:2", text: "When pride cometh, then cometh shame: but with the lowly is wisdom." },
  { ref: "Proverbs 11:3", text: "The integrity of the upright shall guide them: but the perverseness of transgressors shall destroy them." },
  { ref: "Proverbs 11:12", text: "He that is void of wisdom despiseth his neighbour: but a man of understanding holdeth his peace." },
  { ref: "Proverbs 11:14", text: "Where no counsel is, the people fall: but in the multitude of counsellors there is safety." },
  { ref: "Proverbs 11:17", text: "The merciful man doeth good to his own soul: but he that is cruel troubleth his own flesh." },
  { ref: "Proverbs 11:24", text: "There is that scattereth, and yet increaseth; and there is that withholdeth more than is meet, but it tendeth to poverty." },
  { ref: "Proverbs 11:25", text: "The liberal soul shall be made fat: and he that watereth shall be watered also himself." },
  { ref: "Proverbs 11:30", text: "The fruit of the righteous is a tree of life; and he that winneth souls is wise." },
  { ref: "Proverbs 12:1", text: "Whoso loveth instruction loveth knowledge: but he that hateth reproof is brutish." },
  { ref: "Proverbs 12:3", text: "A man shall not be established by wickedness: but the root of the righteous shall not be moved." },
  { ref: "Proverbs 12:11", text: "He that tilleth his land shall be satisfied with bread: but he that followeth vain persons is void of understanding." },
  { ref: "Proverbs 12:15", text: "The way of a fool is right in his own eyes: but he that hearkeneth unto counsel is wise." },
  { ref: "Proverbs 12:18", text: "There is that speaketh like the piercings of a sword: but the tongue of the wise is health." },
  { ref: "Proverbs 12:22", text: "Lying lips are abomination to the LORD: but they that deal truly are his delight." },
  { ref: "Proverbs 12:25", text: "Heaviness in the heart of man maketh it stoop: but a good word maketh it glad." },
  { ref: "Proverbs 12:28", text: "In the way of righteousness is life: and in the pathway thereof there is no death." },
  { ref: "Proverbs 13:3", text: "He that keepeth his mouth keepeth his life: but he that openeth wide his lips shall have destruction." },
  { ref: "Proverbs 13:4", text: "The soul of the sluggard desireth, and hath nothing: but the soul of the diligent shall be made fat." },
  { ref: "Proverbs 13:10", text: "Only by pride cometh contention: but with the well advised is wisdom." },
  { ref: "Proverbs 13:11", text: "Wealth gotten by vanity shall be diminished: but he that gathereth by labour shall increase." },
  { ref: "Proverbs 13:12", text: "Hope deferred maketh the heart sick: but when the desire cometh, it is a tree of life." },
  { ref: "Proverbs 13:19", text: "The desire accomplished is sweet to the soul: but it is abomination to fools to depart from evil." },
  { ref: "Proverbs 13:20", text: "He that walketh with wise men shall be wise: but a companion of fools shall be destroyed." },
  { ref: "Proverbs 13:25", text: "The righteous eateth to the satisfying of his soul: but the belly of the wicked shall want." },
  { ref: "Proverbs 14:12", text: "There is a way which seemeth right unto a man, but the end thereof are the ways of death." },
  { ref: "Proverbs 14:15", text: "The simple believeth every word: but the prudent man looketh well to his going." },
  { ref: "Proverbs 14:16", text: "A wise man feareth, and departeth from evil: but the fool rageth, and is confident." },
  { ref: "Proverbs 14:23", text: "In all labour there is profit: but the talk of the lips tendeth only to penury." },
  { ref: "Proverbs 14:26", text: "In the fear of the LORD is strong confidence: and his children shall have a place of refuge." },
  { ref: "Proverbs 14:27", text: "The fear of the LORD is a fountain of life, to depart from the snares of death." },
  { ref: "Proverbs 14:29", text: "He that is slow to wrath is of great understanding: but he that is hasty of spirit exalteth folly." },
  { ref: "Proverbs 14:30", text: "A sound heart is the life of the flesh: but envy the rottenness of the bones." },
  { ref: "Proverbs 14:34", text: "Righteousness exalteth a nation: but sin is a reproach to any people." },
  { ref: "Proverbs 15:1", text: "A soft answer turneth away wrath: but grievous words stir up anger." },
  { ref: "Proverbs 15:3", text: "The eyes of the LORD are in every place, beholding the evil and the good." },
  { ref: "Proverbs 15:4", text: "A wholesome tongue is a tree of life: but perverseness therein is a breach in the spirit." },
  { ref: "Proverbs 15:6", text: "In the house of the righteous is much treasure: but in the revenues of the wicked is trouble." },
  { ref: "Proverbs 15:13", text: "A merry heart maketh a cheerful countenance: but by sorrow of the heart the spirit is broken." },
  { ref: "Proverbs 15:15", text: "All the days of the afflicted are evil: but he that is of a merry heart hath a continual feast." },
  { ref: "Proverbs 15:16", text: "Better is little with the fear of the LORD than great treasure and trouble therewith." },
  { ref: "Proverbs 15:22", text: "Without counsel purposes are disappointed: but in the multitude of counsellors they are established." },
  { ref: "Proverbs 15:23", text: "A man hath joy by the answer of his mouth: and a word spoken in due season, how good is it!" },
  { ref: "Proverbs 15:30", text: "The light of the eyes rejoiceth the heart: and a good report maketh the bones fat." },
  { ref: "Proverbs 15:33", text: "The fear of the LORD is the instruction of wisdom; and before honour is humility." },
  { ref: "Proverbs 16:3", text: "Commit thy works unto the LORD, and thy thoughts shall be established." },
  { ref: "Proverbs 16:7", text: "When a man's ways please the LORD, he maketh even his enemies to be at peace with him." },
  { ref: "Proverbs 16:8", text: "Better is a little with righteousness than great revenues without right." },
  { ref: "Proverbs 16:9", text: "A man's heart deviseth his way: but the LORD directeth his steps." },
  { ref: "Proverbs 16:16", text: "How much better is it to get wisdom than gold! and to get understanding rather to be chosen than silver!" },
  { ref: "Proverbs 16:18", text: "Pride goeth before destruction, and an haughty spirit before a fall." },
  { ref: "Proverbs 16:20", text: "He that handleth a matter wisely shall find good: and whoso trusteth in the LORD, happy is he." },
  { ref: "Proverbs 16:24", text: "Pleasant words are as an honeycomb, sweet to the soul, and health to the bones." },
  { ref: "Proverbs 16:31", text: "The hoary head is a crown of glory, if it be found in the way of righteousness." },
  { ref: "Proverbs 16:32", text: "He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city." },
  { ref: "Proverbs 17:3", text: "The fining pot is for silver, and the furnace for gold: but the LORD trieth the hearts." },
  { ref: "Proverbs 17:9", text: "He that covereth a transgression seeketh love; but he that repeateth a matter separateth very friends." },
  { ref: "Proverbs 17:17", text: "A friend loveth at all times, and a brother is born for adversity." },
  { ref: "Proverbs 17:22", text: "A merry heart doeth good like a medicine: but a broken spirit drieth the bones." },
  { ref: "Proverbs 17:24", text: "Wisdom is before him that hath understanding; but the eyes of a fool are in the ends of the earth." },
  { ref: "Proverbs 17:27", text: "He that hath knowledge spareth his words: and a man of understanding is of an excellent spirit." },
  { ref: "Proverbs 18:10", text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe." },
  { ref: "Proverbs 18:12", text: "Before destruction the heart of man is haughty, and before honour is humility." },
  { ref: "Proverbs 18:13", text: "He that answereth a matter before he heareth it, it is folly and shame unto him." },
  { ref: "Proverbs 18:16", text: "A man's gift maketh room for him, and bringeth him before great men." },
  { ref: "Proverbs 18:21", text: "Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof." },
  { ref: "Proverbs 18:22", text: "Whoso findeth a wife findeth a good thing, and obtaineth favour of the LORD." },
  { ref: "Proverbs 18:24", text: "A man that hath friends must shew himself friendly: and there is a friend that sticketh closer than a brother." },
  { ref: "Proverbs 19:2", text: "Also, that the soul be without knowledge, it is not good; and he that hasteth with his feet sinneth." },
  { ref: "Proverbs 19:8", text: "He that getteth wisdom loveth his own soul: he that keepeth understanding shall find good." },
  { ref: "Proverbs 19:11", text: "The discretion of a man deferreth his anger; and it is his glory to pass over a transgression." },
  { ref: "Proverbs 19:14", text: "House and riches are the inheritance of fathers: and a prudent wife is from the LORD." },
  { ref: "Proverbs 19:17", text: "He that hath pity upon the poor lendeth unto the LORD; and that which he hath given will he pay him again." },
  { ref: "Proverbs 19:20", text: "Hear counsel, and receive instruction, that thou mayest be wise in thy latter end." },
  { ref: "Proverbs 19:21", text: "There are many devices in a man's heart; nevertheless the counsel of the LORD, that shall stand." },
  { ref: "Proverbs 19:23", text: "The fear of the LORD tendeth to life: and he that hath it shall abide satisfied; he shall not be visited with evil." },
  { ref: "Proverbs 20:3", text: "It is an honour for a man to cease from strife: but every fool will be meddling." },
  { ref: "Proverbs 20:7", text: "The just man walketh in his integrity: his children are blessed after him." },
  { ref: "Proverbs 20:11", text: "Even a child is known by his doings, whether his work be pure, and whether it be right." },
  { ref: "Proverbs 20:15", text: "There is gold, and a multitude of rubies: but the lips of knowledge are a precious jewel." },
  { ref: "Proverbs 20:18", text: "Every purpose is established by counsel: and with good advice make war." },
  { ref: "Proverbs 20:22", text: "Say not thou, I will recompense evil; but wait on the LORD, and he shall save thee." },
  { ref: "Proverbs 20:24", text: "Man's goings are of the LORD; how can a man then understand his own way?" },
  { ref: "Proverbs 20:29", text: "The glory of young men is their strength: and the beauty of old men is the gray head." },
  { ref: "Proverbs 21:1", text: "The king's heart is in the hand of the LORD, as the rivers of water: he turneth it whithersoever he will." },
  { ref: "Proverbs 21:2", text: "Every way of a man is right in his own eyes: but the LORD pondereth the hearts." },
  { ref: "Proverbs 21:3", text: "To do justice and judgment is more acceptable to the LORD than sacrifice." },
  { ref: "Proverbs 21:5", text: "The thoughts of the diligent tend only to plenteousness; but of every one that is hasty only to want." },
  { ref: "Proverbs 21:21", text: "He that followeth after righteousness and mercy findeth life, righteousness, and honour." },
  { ref: "Proverbs 21:23", text: "Whoso keepeth his mouth and his tongue keepeth his soul from troubles." },
  { ref: "Proverbs 21:31", text: "The horse is prepared against the day of battle: but safety is of the LORD." },
  { ref: "Proverbs 22:1", text: "A good name is rather to be chosen than great riches, and loving favour rather than silver and gold." },
  { ref: "Proverbs 22:4", text: "By humility and the fear of the LORD are riches, and honour, and life." },
  { ref: "Proverbs 22:6", text: "Train up a child in the way he should go: and when he is old, he will not depart from it." },
  { ref: "Proverbs 22:9", text: "He that hath a bountiful eye shall be blessed; for he giveth of his bread to the poor." },
  { ref: "Proverbs 22:11", text: "He that loveth pureness of heart, for the grace of his lips the king shall be his friend." },
  { ref: "Proverbs 22:17", text: "Bow down thine ear, and hear the words of the wise, and apply thine heart unto my knowledge." },
  { ref: "Proverbs 22:24", text: "Make no friendship with an angry man; and with a furious man thou shalt not go:" },
  { ref: "Proverbs 22:29", text: "Seest thou a man diligent in his business? he shall stand before kings; he shall not stand before mean men." },
  { ref: "Proverbs 23:4", text: "Labour not to be rich: cease from thine own wisdom." },
  { ref: "Proverbs 23:7", text: "For as he thinketh in his heart, so is he." },
  { ref: "Proverbs 23:12", text: "Apply thine heart unto instruction, and thine ears to the words of knowledge." },
  { ref: "Proverbs 23:17", text: "Let not thine heart envy sinners: but be thou in the fear of the LORD all the day long." },
  { ref: "Proverbs 23:18", text: "For surely there is an end; and thine expectation shall not be cut off." },
  { ref: "Proverbs 23:19", text: "Hear thou, my son, and be wise, and guide thine heart in the way." },
  { ref: "Proverbs 23:23", text: "Buy the truth, and sell it not; also wisdom, and instruction, and understanding." },
  { ref: "Proverbs 23:26", text: "My son, give me thine heart, and let thine eyes observe my ways." },
  { ref: "Proverbs 24:3", text: "Through wisdom is an house builded; and by understanding it is established:" },
  { ref: "Proverbs 24:5", text: "A wise man is strong; yea, a man of knowledge increaseth strength." },
  { ref: "Proverbs 24:10", text: "If thou faint in the day of adversity, thy strength is small." },
  { ref: "Proverbs 24:14", text: "So shall the knowledge of wisdom be unto thy soul: when thou hast found it, then there shall be a reward, and thy expectation shall not be cut off." },
  { ref: "Proverbs 24:16", text: "For a just man falleth seven times, and riseth up again: but the wicked shall fall into mischief." },
  { ref: "Proverbs 24:26", text: "Every man shall kiss his lips that giveth a right answer." },
  { ref: "Proverbs 24:27", text: "Prepare thy work without, and make it fit for thyself in the field; and afterwards build thine house." },
  { ref: "Proverbs 24:29", text: "Say not, I will do so to him as he hath done to me: I will render to the man according to his work." },
  { ref: "Proverbs 24:32", text: "Then I saw, and considered it well: I looked upon it, and received instruction." },
  { ref: "Proverbs 25:11", text: "A word fitly spoken is like apples of gold in pictures of silver." },
  { ref: "Proverbs 25:15", text: "By long forbearing is a prince persuaded, and a soft tongue breaketh the bone." },
  { ref: "Proverbs 25:16", text: "Hast thou found honey? eat so much as is sufficient for thee, lest thou be filled therewith, and vomit it." },
  { ref: "Proverbs 25:21", text: "If thine enemy be hungry, give him bread to eat; and if he be thirsty, give him water to drink:" },
  { ref: "Proverbs 25:28", text: "He that hath no rule over his own spirit is like a city that is broken down, and without walls." },
  { ref: "Proverbs 26:12", text: "Seest thou a man wise in his own conceit? there is more hope of a fool than of him." },
  { ref: "Proverbs 26:20", text: "Where no wood is, there the fire goeth out: so where there is no talebearer, the strife ceaseth." },
  { ref: "Proverbs 26:27", text: "Whoso diggeth a pit shall fall therein: and he that rolleth a stone, it will return upon him." },
  { ref: "Proverbs 27:1", text: "Boast not thyself of to morrow; for thou knowest not what a day may bring forth." },
  { ref: "Proverbs 27:2", text: "Let another man praise thee, and not thine own mouth; a stranger, and not thine own lips." },
  { ref: "Proverbs 27:5", text: "Open rebuke is better than secret love." },
  { ref: "Proverbs 27:6", text: "Faithful are the wounds of a friend; but the kisses of an enemy are deceitful." },
  { ref: "Proverbs 27:9", text: "Ointment and perfume rejoice the heart: so doth the sweetness of a man's friend by hearty counsel." },
  { ref: "Proverbs 27:12", text: "A prudent man foreseeth the evil, and hideth himself; but the simple pass on, and are punished." },
  { ref: "Proverbs 27:17", text: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend." },
  { ref: "Proverbs 27:19", text: "As in water face answereth to face, so the heart of man to man." },
  { ref: "Proverbs 27:21", text: "As the fining pot for silver, and the furnace for gold; so is a man to his praise." },
  { ref: "Proverbs 27:23", text: "Be thou diligent to know the state of thy flocks, and look well to thy herds." },
  { ref: "Proverbs 28:1", text: "The wicked flee when no man pursueth: but the righteous are bold as a lion." },
  { ref: "Proverbs 28:6", text: "Better is the poor that walketh in his uprightness, than he that is perverse in his ways, though he be rich." },
  { ref: "Proverbs 28:13", text: "He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy." },
  { ref: "Proverbs 28:14", text: "Happy is the man that feareth alway: but he that hardeneth his heart shall fall into mischief." },
  { ref: "Proverbs 28:20", text: "A faithful man shall abound with blessings: but he that maketh haste to be rich shall not be innocent." },
  { ref: "Proverbs 28:25", text: "He that is of a proud heart stirreth up strife: but he that putteth his trust in the LORD shall be made fat." },
  { ref: "Proverbs 28:26", text: "He that trusteth in his own heart is a fool: but whoso walketh wisely, he shall be delivered." },
  { ref: "Proverbs 29:2", text: "When the righteous are in authority, the people rejoice: but when the wicked beareth rule, the people mourn." },
  { ref: "Proverbs 29:11", text: "A fool uttereth all his mind: but a wise man keepeth it in till afterwards." },
  { ref: "Proverbs 29:18", text: "Where there is no vision, the people perish: but he that keepeth the law, happy is he." },
  { ref: "Proverbs 29:23", text: "A man's pride shall bring him low: but honour shall uphold the humble in spirit." },
  { ref: "Proverbs 29:25", text: "The fear of man bringeth a snare: but whoso putteth his trust in the LORD shall be safe." },
  { ref: "Proverbs 30:5", text: "Every word of God is pure: he is a shield unto them that put their trust in him." },
  { ref: "Proverbs 30:8", text: "Remove far from me vanity and lies: give me neither poverty nor riches; feed me with food convenient for me:" },
  { ref: "Proverbs 30:24", text: "There be four things which are little upon the earth, but they are exceeding wise:" },
  { ref: "Proverbs 30:32", text: "If thou hast done foolishly in lifting up thyself, or if thou hast thought evil, lay thine hand upon thy mouth." },
  { ref: "Proverbs 31:8", text: "Open thy mouth for the dumb in the cause of all such as are appointed to destruction." },
  { ref: "Proverbs 31:9", text: "Open thy mouth, judge righteously, and plead the cause of the poor and needy." },
  { ref: "Proverbs 31:10", text: "Who can find a virtuous woman? for her price is far above rubies." },
  { ref: "Proverbs 31:25", text: "Strength and honour are her clothing; and she shall rejoice in time to come." },
  { ref: "Proverbs 31:26", text: "She openeth her mouth with wisdom; and in her tongue is the law of kindness." },
  { ref: "Proverbs 31:30", text: "Favour is deceitful, and beauty is vain: but a woman that feareth the LORD, she shall be praised." },
];

export function getDailyVerse(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date - start;
  const day = Math.floor(diff / 86400000);

  return proverbs[(day - 1) % proverbs.length];
}